In [2]:
import pandas as pd

In [27]:
start_df = pd.read_csv("data/start.csv", names=['symbol','shares_held'])
trades_df = pd.read_csv("data/trades.csv", names=['symbol','trade_amount'])

In [28]:
trades_df.head()

  symbol  trade_amount
0    CAT        847533
1     EL        162298
2    KMX        220487
3    NSC        965676
4     PM        636000

In [29]:
start_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 363 entries, 0 to 362
Data columns (total 2 columns):
symbol         363 non-null object
shares_held    363 non-null int64
dtypes: int64(1), object(1)
memory usage: 5.8+ KB

In [30]:
# No empty values present in the start.csv file

In [31]:
trades_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18633 entries, 0 to 18632
Data columns (total 2 columns):
symbol          18633 non-null object
trade_amount    18633 non-null int64
dtypes: int64(1), object(1)
memory usage: 291.2+ KB

In [32]:
# No empty values present in trades.csv either

In [33]:
start_df.head()

  symbol  shares_held
0    MMM       293738
1    ABT      -306281
2   ABBV      -696534
3    AAP      -638384
4    AES       724516

In [36]:
start_df.set_index('symbol')
trades_df.set_index('symbol')

# We set index_col to be the symbols column, to allow for easy access of
# individual companies

        trade_amount
symbol
CAT           847533
EL            162298
KMX           220487
NSC           965676
PM            636000
JEF          -496261
PGR          -802709
CI            228949
KO           -290879
FBHS          970031
TSS           874314
KSU          -984428
AIG           116289
NOV            20047
PSA           -74075
MPC          -267736
FRT           673503
XEL           118039
BAC           868503
MRK           887394
VTR           780624
AOS           528006
PM            395926
JWN           132669
CMS           278661
DWDP          610253
PFE           216863
DG           -988103
C            -371139
HAL           554115
...              ...
SPG          -840853
PHM           235838
FMC          -738502
KO            -33562
LMT          -317622
MSI           862199
CL            154305
PNC           585608
BF.B          883487
KSU           915436
CRM           671983
ED            478010
MCD          -986742
ECL          -184251
HFC           782197
TMK           -90229
AES            49429
CXO           -93338
COG           917210
MCK          -567533
MHK          -425511
NCLH         -690802
FBHS          303504
HRS          -282409
JEC          -817861
CXO          -693011
AGN           775227
GPN           394318
CNC           322371
PHM          -578484

[18633 rows x 1 columns]

In [37]:
start_df.loc['MMM']

KeyError: 'the label [MMM] is not in the [index]'

In [41]:
start_df.set_index('symbol',inplace=True)

KeyError: 'symbol'

In [42]:
start_df.loc['MMM']

shares_held    293738
Name: MMM, dtype: int64

In [43]:
temp_val = start_df.loc['MMM']

In [44]:
temp_val

shares_held    293738
Name: MMM, dtype: int64

In [45]:
start_df.loc['MMM'] = 293740

In [52]:
start_df.loc['MMM'] = temp_val

In [53]:
start_df.loc['MMM']

shares_held    293738
Name: MMM, dtype: int64

temp_val

In [51]:
temp_val = 293738

In [55]:
trades_df.set_index('symbol',inplace=True)

In [60]:
trades_df.loc['MMM'].sum()

trade_amount   -79542
dtype: int64

In [67]:
start_df.index.values[0]

'MMM'

In [68]:
MMM_value = trades_df.loc[start_df.index.values[0]].sum()

In [70]:
MMM_value

trade_amount   -79542
dtype: int64

In [95]:
'AXP' in trades_df.index

False

In [144]:
end_dict = {}
count = 0

for i in start_df.index.values:
    try:
        end_dict[i] = trades_df.loc[i].sum().values[0] + start_df.loc[i].values[0]
        count +=1
    except:
        if i in trades_df.index:
            print(i,1)
            # These symbols only have one trade in the trades_df
            # Hence just need to add that trade to the starting position
            end_dict[i] = (trades_df.loc[i].sum() + start_df.loc[i]).values[0]
            count +=1
        else:
            print(i,2)
            # These symbols were not traded, hence end of day position
            # is same as start position
            end_dict[i] = start_df.loc[i].values[0]
            count+=1


print(count)


# [(start_df.loc[i] + trades_df.loc[i].sum()) for i in start_df.index.values]

AXP 2
AIZ 2
T 2
IBM 1
LOW 1
WRK 1
363

In [145]:
end_dict

{'MMM': 214196,
 'ABT': 878535,
 'ABBV': -1556626,
 'AAP': -3298989,
 'AES': -609290,
 'AMG': 4195173,
 'AFL': 4493323,
 'A': 1864817,
 'APD': -1261480,
 'ALK': 6594897,
 'ALB': 5744460,
 'ARE': -2096395,
 'ALLE': -873749,
 'AGN': -1384731,
 'LNT': -587980,
 'AEE': -1520723,
 'AEP': 3351904,
 'AXP': 870599,
 'AIG': -994018,
 'AMT': 10909653,
 'AWK': -3295931,
 'AMP': 250497,
 'ABC': 2436387,
 'AME': -3448049,
 'APH': 1581198,
 'APC': 478492,
 'ANTM': -1006987,
 'AON': -1241761,
 'AOS': 4026410,
 'APA': 8696316,
 'AIV': -5605954,
 'APTV': 4958965,
 'ADM': -794997,
 'ARNC': 1874788,
 'ANET': 3829153,
 'AJG': 116315,
 'AIZ': -18026,
 'ATO': 3925968,
 'T': -75799,
 'AZO': -40409,
 'AVB': -1928305,
 'AVY': -5374133,
 'BHGE': -522185,
 'BLL': -771741,
 'BAC': 12464397,
 'BK': 13765662,
 'BAX': 5751647,
 'BBT': -2551081,
 'BDX': 2217122,
 'BRK.B': 6992315,
 'BBY': 1139714,
 'BLK': -2389512,
 'HRB': -284362,
 'BA': -5200761,
 'BWA': 498524,
 'BXP': 1216909,
 'BSX': -522166,
 'BMY': 6223224,
 'BR': -1676594,
 'BF.B': -3944374,
 'COG': -3423248,
 'CPB': 4165093,
 'COF': -3105033,
 'CPRI': 8212511,
 'CAH': 1756866,
 'KMX': 4051352,
 'CCL': 549123,
 'CAT': -5382807,
 'CBRE': 959464,
 'CBS': 3266216,
 'CE': 3065958,
 'CNC': -3739803,
 'CNP': 2304328,
 'CTL': -442364,
 'CF': -4267121,
 'SCHW': -1201351,
 'CVX': 1174598,
 'CMG': 5119405,
 'CB': 3493942,
 'CHD': 4271850,
 'CI': 3375876,
 'XEC': -6800347,
 'C': -994009,
 'CFG': -835950,
 'CLX': 2340523,
 'CMS': 2633103,
 'KO': 4573101,
 'CL': 3137126,
 'CMA': 2500225,
 'CAG': 4327219,
 'CXO': -2860614,
 'COP': -4337348,
 'ED': 5063836,
 'COO': -5914171,
 'GLW': 1509953,
 'COTY': 5736714,
 'CCI': -2380043,
 'CMI': -293589,
 'CVS': 3596601,
 'DHI': -6502147,
 'DHR': -695842,
 'DRI': -6292473,
 'DVA': -7543973,
 'DE': 6244917,
 'DAL': 4872200,
 'DVN': -2415481,
 'DLR': -4716611,
 'DFS': 812695,
 'DG': -193305,
 'D': -4367545,
 'DOV': 1534440,
 'DOW': -10183553,
 'DWDP': -3344364,
 'DTE': -719537,
 'DRE': -5276408,
 'DUK': -1494688,
 'DXC': -290781,
 'EMN': -3263305,
 'ETN': -931851,
 'ECL': 2929274,
 'EIX': 614171,
 'EW': -3744038,
 'EMR': -918817,
 'ETR': -510641,
 'EOG': 6077402,
 'EFX': -2588261,
 'EQR': 593082,
 'ESS': 1029207,
 'EL': 7054649,
 'EVRG': 1663858,
 'ES': -1346842,
 'RE': -1669199,
 'EXC': 3635563,
 'EXR': 4897175,
 'XOM': 6526946,
 'FRT': -2411816,
 'FDX': 3811194,
 'FIS': 3584326,
 'FE': -1865029,
 'FRC': 13066573,
 'FLT': 1614692,
 'FLS': 1870142,
 'FLR': -8034887,
 'FMC': -5698786,
 'FL': -2374981,
 'F': 2331353,
 'FTV': -1254939,
 'FBHS': 11888715,
 'BEN': 5016653,
 'GPS': 2663869,
 'IT': -2157324,
 'GD': -2826199,
 'GE': 2588101,
 'GIS': -372052,
 'GM': -4373816,
 'GPC': 4431395,
 'GPN': 61397,
 'GS': 1969784,
 'GWW': -10796241,
 'HAL': 4142169,
 'HBI': -4326904,
 'HOG': -1363090,
 'HRS': 6940463,
 'HIG': -2251880,
 'HCA': 4245115,
 'HCP': 4774150,
 'HP': 8396347,
 'HSY': 567625,
 'HES': 2555993,
 'HPE': 4506849,
 'HLT': -10061553,
 'HFC': 1223904,
 'HD': 1694601,
 'HON': 216239,
 'HRL': -1068368,
 'HST': 269277,
 'HPQ': -3034370,
 'HUM': 5199627,
 'HII': 2654351,
 'ITW': -8713756,
 'IR': -5760816,
 'ICE': -1071768,
 'IBM': -1334820,
 'IP': 1111374,
 'IPG': 1014509,
 'IFF': -5336103,
 'IVZ': 3178292,
 'IQV': 29843,
 'IRM': -2373505,
 'JEC': 1330644,
 'JEF': -72482,
 'SJM': -5069890,
 'JNJ': -208822,
 'JCI': 1116339,
 'JPM': 656360,
 'JNPR': 2072594,
 'KSU': -2049874,
 'K': 2006834,
 'KEY': -3505970,
 'KEYS': -6942517,
 'KMB': 6233700,
 'KIM': 3544282,
 'KSS': -1104725,
 'KR': -4028704,
 'LB': -3223433,
 'LLL': 1031262,
 'LH': -2246349,
 'LEG': -807891,
 'LEN': -9525232,
 'LLY': -8289855,
 'LNC': -2675164,
 'LIN': 5850706,
 'LMT': -747139,
 'L': -539929,
 'LOW': 1311906,
 'LYB': 3888574,
 'MTB': -485217,
 'MAC': -4346813,
 'MRO': 4624161,
 'MPC': -2063695,
 'MMC': 898804,
 'MLM': -2685190,
 'MAS': -3713843,
 'MA': 639185,
 'MKC': 405047,
 'MCD': -10076081,
 'MCK': 5133696,
 'MDT': 7746943,
 'MRK': -3461072,
 'MET': -4975198,
 'MTD': -1437036,
 'MGM': 5036417,
 'MAA': -98135,
 'MHK': -6083201,
 'TAP': 1583385,
 'MCO': 2764172,
 'MS': 70904,
 'MOS': -1909807,
 'MSI': 11390567,
 'MSCI': 442247,
 'NOV': 2358289,
 'NEM': -2481034,
 'NEE': 3992629,
 'NLSN': 5841108,
 'NKE': -774487,
 'NI': 1970770,
 'NBL': 2267303,
 'JWN': 6131818,
 'NSC': 6009018,
 'NOC': -584005,
 'NCLH': 1648414,
 'NRG': -5448073,
 'NUE': -479815,
 'OXY': 3033326,
 'OMC': 3054631,
 'OKE': 412411,
 'ORCL': -1706687,
 'PKG': 870398,
 'PH': 6681572,
 'PNR': -1208982,
 'PKI': -1593328,
 'PRGO': 3859618,
 'PFE': 1655564,
 'PM': -10211561,
 'PSX': -1198193,
 'PNW': 8637218,
 'PXD': -2567555,
 'PNC': -11608088,
 'PPG': -394725,
 'PPL': 1551297,
 'PFG': 180806,
 'PG': -1850410,
 'PGR': -2351514,
 'PLD': -470029,
 'PRU': 3583943,
 'PEG': 1427343,
 'PSA': -3448681,
 'PHM': 5739062,
 'PWR': -6036743,
 'RL': -2108124,
 'RJF': 472496,
 'RTN': -1428496,
 'O': 498808,
 'RHT': -4997124,
 'REG': -824547,
 'RF': -2252223,
 'RSG': 7382695,
 'RMD': 2714803,
 'RHI': 3322955,
 'ROK': -443228,
 'ROL': -1352985,
 'ROP': -98060,
 'RCL': 1911317,
 'CRM': 860794,
 'SLB': 2142144,
 'SEE': 1502796,
 'SRE': 99586,
 'SHW': -678332,
 'SPG': -3778752,
 'SLG': 132835,
 'SO': -932826,
 'LUV': -4555163,
 'SPGI': 3124554,
 'SWK': -6413733,
 'STT': -2904720,
 'SYK': 3259127,
 'STI': 532631,
 'SYF': 2302898,
 'SYY': 2496707,
 'TPR': 7034450,
 'TGT': 747841,
 'TEL': 4575790,
 'FTI': -36125,
 'TFX': 3690356,
 'TXT': 2474523,
 'TMO': 522333,
 'TIF': -1605930,
 'TWTR': 6203610,
 'TJX': -563076,
 'TMK': -2442663,
 'TSS': 5616866,
 'TDG': -888030,
 'TRV': 379759,
 'TSN': 1093094,
 'UDR': -181990,
 'USB': 1672854,
 'UAA': -3223877,
 'UA': 2425686,
 'UAL': 1713925,
 'UNH': 11596195,
 'UPS': 1046315,
 'URI': 266348,
 'UTX': 2129526,
 'UHS': -97769,
 'UNM': 1732079,
 'VFC': -3847402,
 'VLO': -1398964,
 'VAR': 3289555,
 'VTR': -3794962,
 'VZ': -674354,
 'V': -1731838,
 'VNO': -7210963,
 'VMC': -1540938,
 'WAB': 497171,
 'WMT': 9418520,
 'DIS': 5196969,
 'WM': 2459997,
 'WAT': -4971337,
 'WEC': 6245290,
 'WCG': -3640310,
 'WFC': -86434,
 'WELL': 1096669,
 'WU': -4894310,
 'WRK': 100800,
 'WY': 338046,
 'WHR': -5711439,
 'WMB': -2900528,
 'XEL': -738406,
 'XRX': 951896,
 'XYL': -359012,
 'YUM': -3013298,
 'ZBH': 187439,
 'ZTS': 6890776}

In [148]:
end_df = pd.DataFrame.from_dict(end_dict,orient="index")
end_df.columns = ['shares_held']
end_df.index.name = 'symbol'
end_df.loc['AXP']

shares_held    870599
Name: AXP, dtype: int64

In [151]:
end_df.drop_duplicates(inplace=True)
end_df.to_csv('eod.csv')

In [110]:
end_dict

{'MMM': 214196,
 'ABT': 878535,
 'ABBV': -1556626,
 'AAP': -3298989,
 'AES': -609290,
 'AMG': 4195173,
 'AFL': 4493323,
 'A': 1864817,
 'APD': -1261480,
 'ALK': 6594897,
 'ALB': 5744460,
 'ARE': -2096395,
 'ALLE': -873749,
 'AGN': -1384731,
 'LNT': -587980,
 'AEE': -1520723,
 'AEP': 3351904,
 'AIG': -994018,
 'AMT': 10909653,
 'AWK': -3295931,
 'AMP': 250497,
 'ABC': 2436387,
 'AME': -3448049,
 'APH': 1581198,
 'APC': 478492,
 'ANTM': -1006987,
 'AON': -1241761,
 'AOS': 4026410,
 'APA': 8696316,
 'AIV': -5605954,
 'APTV': 4958965,
 'ADM': -794997,
 'ARNC': 1874788,
 'ANET': 3829153,
 'AJG': 116315,
 'ATO': 3925968,
 'AZO': -40409,
 'AVB': -1928305,
 'AVY': -5374133,
 'BHGE': -522185,
 'BLL': -771741,
 'BAC': 12464397,
 'BK': 13765662,
 'BAX': 5751647,
 'BBT': -2551081,
 'BDX': 2217122,
 'BRK.B': 6992315,
 'BBY': 1139714,
 'BLK': -2389512,
 'HRB': -284362,
 'BA': -5200761,
 'BWA': 498524,
 'BXP': 1216909,
 'BSX': -522166,
 'BMY': 6223224,
 'BR': -1676594,
 'BF.B': -3944374,
 'COG': -3423248,
 'CPB': 4165093,
 'COF': -3105033,
 'CPRI': 8212511,
 'CAH': 1756866,
 'KMX': 4051352,
 'CCL': 549123,
 'CAT': -5382807,
 'CBRE': 959464,
 'CBS': 3266216,
 'CE': 3065958,
 'CNC': -3739803,
 'CNP': 2304328,
 'CTL': -442364,
 'CF': -4267121,
 'SCHW': -1201351,
 'CVX': 1174598,
 'CMG': 5119405,
 'CB': 3493942,
 'CHD': 4271850,
 'CI': 3375876,
 'XEC': -6800347,
 'C': -994009,
 'CFG': -835950,
 'CLX': 2340523,
 'CMS': 2633103,
 'KO': 4573101,
 'CL': 3137126,
 'CMA': 2500225,
 'CAG': 4327219,
 'CXO': -2860614,
 'COP': -4337348,
 'ED': 5063836,
 'COO': -5914171,
 'GLW': 1509953,
 'COTY': 5736714,
 'CCI': -2380043,
 'CMI': -293589,
 'CVS': 3596601,
 'DHI': -6502147,
 'DHR': -695842,
 'DRI': -6292473,
 'DVA': -7543973,
 'DE': 6244917,
 'DAL': 4872200,
 'DVN': -2415481,
 'DLR': -4716611,
 'DFS': 812695,
 'DG': -193305,
 'D': -4367545,
 'DOV': 1534440,
 'DOW': -10183553,
 'DWDP': -3344364,
 'DTE': -719537,
 'DRE': -5276408,
 'DUK': -1494688,
 'DXC': -290781,
 'EMN': -3263305,
 'ETN': -931851,
 'ECL': 2929274,
 'EIX': 614171,
 'EW': -3744038,
 'EMR': -918817,
 'ETR': -510641,
 'EOG': 6077402,
 'EFX': -2588261,
 'EQR': 593082,
 'ESS': 1029207,
 'EL': 7054649,
 'EVRG': 1663858,
 'ES': -1346842,
 'RE': -1669199,
 'EXC': 3635563,
 'EXR': 4897175,
 'XOM': 6526946,
 'FRT': -2411816,
 'FDX': 3811194,
 'FIS': 3584326,
 'FE': -1865029,
 'FRC': 13066573,
 'FLT': 1614692,
 'FLS': 1870142,
 'FLR': -8034887,
 'FMC': -5698786,
 'FL': -2374981,
 'F': 2331353,
 'FTV': -1254939,
 'FBHS': 11888715,
 'BEN': 5016653,
 'GPS': 2663869,
 'IT': -2157324,
 'GD': -2826199,
 'GE': 2588101,
 'GIS': -372052,
 'GM': -4373816,
 'GPC': 4431395,
 'GPN': 61397,
 'GS': 1969784,
 'GWW': -10796241,
 'HAL': 4142169,
 'HBI': -4326904,
 'HOG': -1363090,
 'HRS': 6940463,
 'HIG': -2251880,
 'HCA': 4245115,
 'HCP': 4774150,
 'HP': 8396347,
 'HSY': 567625,
 'HES': 2555993,
 'HPE': 4506849,
 'HLT': -10061553,
 'HFC': 1223904,
 'HD': 1694601,
 'HON': 216239,
 'HRL': -1068368,
 'HST': 269277,
 'HPQ': -3034370,
 'HUM': 5199627,
 'HII': 2654351,
 'ITW': -8713756,
 'IR': -5760816,
 'ICE': -1071768,
 'IP': 1111374,
 'IPG': 1014509,
 'IFF': -5336103,
 'IVZ': 3178292,
 'IQV': 29843,
 'IRM': -2373505,
 'JEC': 1330644,
 'JEF': -72482,
 'SJM': -5069890,
 'JNJ': -208822,
 'JCI': 1116339,
 'JPM': 656360,
 'JNPR': 2072594,
 'KSU': -2049874,
 'K': 2006834,
 'KEY': -3505970,
 'KEYS': -6942517,
 'KMB': 6233700,
 'KIM': 3544282,
 'KSS': -1104725,
 'KR': -4028704,
 'LB': -3223433,
 'LLL': 1031262,
 'LH': -2246349,
 'LEG': -807891,
 'LEN': -9525232,
 'LLY': -8289855,
 'LNC': -2675164,
 'LIN': 5850706,
 'LMT': -747139,
 'L': -539929,
 'LYB': 3888574,
 'MTB': -485217,
 'MAC': -4346813,
 'MRO': 4624161,
 'MPC': -2063695,
 'MMC': 898804,
 'MLM': -2685190,
 'MAS': -3713843,
 'MA': 639185,
 'MKC': 405047,
 'MCD': -10076081,
 'MCK': 5133696,
 'MDT': 7746943,
 'MRK': -3461072,
 'MET': -4975198,
 'MTD': -1437036,
 'MGM': 5036417,
 'MAA': -98135,
 'MHK': -6083201,
 'TAP': 1583385,
 'MCO': 2764172,
 'MS': 70904,
 'MOS': -1909807,
 'MSI': 11390567,
 'MSCI': 442247,
 'NOV': 2358289,
 'NEM': -2481034,
 'NEE': 3992629,
 'NLSN': 5841108,
 'NKE': -774487,
 'NI': 1970770,
 'NBL': 2267303,
 'JWN': 6131818,
 'NSC': 6009018,
 'NOC': -584005,
 'NCLH': 1648414,
 'NRG': -5448073,
 'NUE': -479815,
 'OXY': 3033326,
 'OMC': 3054631,
 'OKE': 412411,
 'ORCL': -1706687,
 'PKG': 870398,
 'PH': 6681572,
 'PNR': -1208982,
 'PKI': -1593328,
 'PRGO': 3859618,
 'PFE': 1655564,
 'PM': -10211561,
 'PSX': -1198193,
 'PNW': 8637218,
 'PXD': -2567555,
 'PNC': -11608088,
 'PPG': -394725,
 'PPL': 1551297,
 'PFG': 180806,
 'PG': -1850410,
 'PGR': -2351514,
 'PLD': -470029,
 'PRU': 3583943,
 'PEG': 1427343,
 'PSA': -3448681,
 'PHM': 5739062,
 'PWR': -6036743,
 'RL': -2108124,
 'RJF': 472496,
 'RTN': -1428496,
 'O': 498808,
 'RHT': -4997124,
 'REG': -824547,
 'RF': -2252223,
 'RSG': 7382695,
 'RMD': 2714803,
 'RHI': 3322955,
 'ROK': -443228,
 'ROL': -1352985,
 'ROP': -98060,
 'RCL': 1911317,
 'CRM': 860794,
 'SLB': 2142144,
 'SEE': 1502796,
 'SRE': 99586,
 'SHW': -678332,
 'SPG': -3778752,
 'SLG': 132835,
 'SO': -932826,
 'LUV': -4555163,
 'SPGI': 3124554,
 'SWK': -6413733,
 'STT': -2904720,
 'SYK': 3259127,
 'STI': 532631,
 'SYF': 2302898,
 'SYY': 2496707,
 'TPR': 7034450,
 'TGT': 747841,
 'TEL': 4575790,
 'FTI': -36125,
 'TFX': 3690356,
 'TXT': 2474523,
 'TMO': 522333,
 'TIF': -1605930,
 'TWTR': 6203610,
 'TJX': -563076,
 'TMK': -2442663,
 'TSS': 5616866,
 'TDG': -888030,
 'TRV': 379759,
 'TSN': 1093094,
 'UDR': -181990,
 'USB': 1672854,
 'UAA': -3223877,
 'UA': 2425686,
 'UAL': 1713925,
 'UNH': 11596195,
 'UPS': 1046315,
 'URI': 266348,
 'UTX': 2129526,
 'UHS': -97769,
 'UNM': 1732079,
 'VFC': -3847402,
 'VLO': -1398964,
 'VAR': 3289555,
 'VTR': -3794962,
 'VZ': -674354,
 'V': -1731838,
 'VNO': -7210963,
 'VMC': -1540938,
 'WAB': 497171,
 'WMT': 9418520,
 'DIS': 5196969,
 'WM': 2459997,
 'WAT': -4971337,
 'WEC': 6245290,
 'WCG': -3640310,
 'WFC': -86434,
 'WELL': 1096669,
 'WU': -4894310,
 'WY': 338046,
 'WHR': -5711439,
 'WMB': -2900528,
 'XEL': -738406,
 'XRX': 951896,
 'XYL': -359012,
 'YUM': -3013298,
 'ZBH': 187439,
 'ZTS': 6890776}

In [111]:
start_df.loc['MMM']

shares_held    293738
Name: MMM, dtype: int64

In [112]:
trades_df.loc['MMM'].sum()

trade_amount   -79542
dtype: int64

In [113]:
293738 - 79542

214196